### ISSUE TITLE
Set up branch protection enforcement workflow with GitHub Actions

### ISSUE THREAD

**Issue by mufeedz** [mufeedz/alameen#24]
**Instructions for Copilot agent:**

1. If the dev branch does not exist, create it from main:
   ```
   git checkout main
   git pull
   git checkout -b dev
   git push -u origin dev
   ```

2. Add the following GitHub Actions workflow at `.github/workflows/branch-protection-enforcer.yml`:

   ```yaml
   name: Enforce Branch Protections

   on:
     pull_request:
       branches:
         - main
     push:
       branches:
         - main
         - dev
     delete:
       branches:
         - main
         - dev

   jobs:
     pr_source_to_main:
       if: github.event_name == 'pull_request'
       runs-on: ubuntu-latest
       steps:
         - name: Block PRs to main unless from dev
           if: github.head_ref != 'dev'
           run: |
             echo "❌ Only PRs from 'dev' are allowed to be merged into 'main'."
             exit 1

     block_direct_push:
       if: github.event_name == 'push'
       runs-on: ubuntu-latest
       steps:
         - name: Block direct push to protected branches
           run: |
             echo "❌ Direct pushes to 'main' or 'dev' are not allowed. Please use Pull Requests."
             exit 1

     block_deletion:
       if: github.event_name == 'delete'
       runs-on: ubuntu-latest
       steps:
         - name: Prevent deletion of main or dev
           run: |
             echo "❌ Deletion of 'main' or 'dev' branches is not allowed."
             exit 1
   ```

3. Requirements:
   - Ensure the dev branch exists (create from main if needed).
   - Only allow PRs from dev to main; block all other PRs to main.
   - Block direct pushes to main and dev (require PRs for all changes).
   - Block deletion of main and dev branches.
   - Use the provided workflow YAML file for automation.
